# Generated by Django 4.0.4 on 2022-05-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the car.', max_length=70)),
                ('manufacture_date', models.DateField(verbose_name='Date the car was manufactured.')),
                ('plate_no', models.CharField(max_length=20, verbose_name='Plate number of the car.')),
            ],
        ),
        migrations.CreateModel(
            name='CarImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INTERNATIONAL', 'International'), ('LOCAL', 'Local'), ('INTER-LOCAL', 'Inter-Local')], max_length=20, verbose_name='The role this importer had in the car.')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.car')),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text="The importer's first name or names.", max_length=50)),
                ('last_names', models.CharField(help_text="The importer's last name or names.", max_length=50)),
                ('email', models.EmailField(help_text='The contact email for the importer.', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Manufacturer.', max_length=50)),
                ('website', models.URLField(help_text="The Manufacturer's website.")),
                ('email', models.EmailField(help_text="The Manufacturer's email address.", max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookContributor',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='carimporter',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.importer'),
        ),
        migrations.AddField(
            model_name='car',
            name='importers',
            field=models.ManyToManyField(through='store.CarImporter', to='store.importer'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.manufacturer'),
        ),
        migrations.AddField(
            model_name='review',
            name='car',
            field=models.ForeignKey(default=None, help_text='The Car that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='store.car'),
            preserve_default=False,
        ),
    ]
