# Generated by Django 4.0.4 on 2022-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_car_carimporter_importer_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.CharField(default=None, max_length=20, verbose_name='total_mileage'),
            preserve_default=False,
        ),
    ]
