# Generated by Django 4.0.4 on 2022-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_title_car_name_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=None, verbose_name='current price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=20, verbose_name='total mileage'),
        ),
    ]
