# Generated by Django 4.0.4 on 2022-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_car_price_alter_car_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='plate_no',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default=None, max_length=20, verbose_name='Fuel option.'),
            preserve_default=False,
        ),
    ]
