# Generated by Django 4.0.4 on 2022-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_car_plate_no_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimporter',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
            preserve_default=False,
        ),
    ]
