# Generated by Django 4.0.4 on 2022-06-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_carimporter_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimporter',
            old_name='image',
            new_name='car_image',
        ),
    ]
