# Generated by Django 4.0.4 on 2022-06-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_image_carimporter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimporter',
            name='car_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
