# Generated by Django 4.0.4 on 2022-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_carimporter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimporter',
            name='car_image',
        ),
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
