# Generated by Django 4.0.4 on 2022-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_carimporter_car_image_car_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_image',
            new_name='image',
        ),
    ]
