# Generated by Django 4.0.4 on 2022-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='carzone/templates/profile.jpeg', null=True, upload_to='store/%Y/%m/%d'),
        ),
    ]
